name: Java
description: Install JDK for Android builds.

inputs:
  version:
    description: "JDK version"
    required: false
    default: '17'

runs:
  using: composite
  steps:
    - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
      with:
        distribution: temurin
        java-version: ${{ inputs.version }}
