name: Java
description: Install JDK for Android builds.

inputs:
  version:
    description: "JDK version"
    required: false
    default: '17'

runs:
  using: composite
  steps:
    - uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
      with:
        distribution: temurin
        java-version: ${{ inputs.version }}
