name: Java
description: Install JDK for Android builds.

inputs:
  version:
    description: "JDK version"
    required: false
    default: '17'

runs:
  using: composite
  steps:
    - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        distribution: temurin
        java-version: ${{ inputs.version }}
